#!/usr/bin/env sh

set -m;

mosquitto --config-file /mosquitto/config/mosquitto.conf &
timeout 1m sh -c "until nc -z 127.0.0.1 1883; do sleep 1; done" # @todo port could be set dynamically
echo "@todo run Python script here"

fg %1
